name: Tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: [8.1, 8.0, 7.4]
                dependency-version: [prefer-lowest, prefer-stable]

        name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ~/.composer/cache/files
                    key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                    coverage: none

            -   name: Install dependencies
                run: composer update --no-interaction --prefer-source

            -   name: Execute tests
                run: vendor/bin/phpunit

    codecov:

        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP (with Xdebug)
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
                  coverage: xdebug

            - name: Check PHP Version
              run: php -v

            - name: Install Dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Tests With Code Coverage
              run: "vendor/bin/phpunit tests/ --coverage-filter=src/ --coverage-clover=coverage.xml"

            - name: "Send code coverage report to Codecov.io"
              env:
                  CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
              run: "bash <(curl -s https://codecov.io/bash) || true"